name: publish
on: [push]
jobs:
 publish-hello-docker-image:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: Login to GitHub Container Registry
     uses: docker/login-action@v1
     with:
      registry: ghcr.io
      username: ${{ secrets.GH_USERNAME }}
      password: ${{ secrets.GH_PASSWORD }}
   - name: Build the Hello World Docker image
     run: |
       docker build . --tag ghcr.io/jmnordeste-dev/tanzu-lab-container-reg:latest
       docker run ghcr.io/jmnordeste-dev/tanzu-lab-container-reg:latest
       docker push ghcr.io/jmnordeste-dev/tanzu-lab-container-reg:latest
